language: python
dist: xenial
sudo: required
env:
python:
    - "3.7"
    - "3.8-dev"
install:
    - "make setup"
    - "pip install ."
script:
    - "make test"
after_success:
    - "codcov"
    - "coveralls"
matrix:
    allow_failures:
        - python: "3.8-dev"
    include:
        - python: "3.6"
          env: LINTING=true
          script:
              - "make lint test"
